version: '3.3'

services:
  # Apache with PHP container
  web:
    build:
      context: .  # Use the Dockerfile in the current directory to build the image
    container_name: flour_mill_web
    volumes:
      - ./src:/var/www/html  # Mount the src directory where your PHP files are
    ports:
      - "8080:80"            # Expose the web service on port 8080
    depends_on:
      - db
    networks:
      - flour_mill_net
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=flour_mill

  # MySQL container
  db:
    image: mysql:5.7
    container_name: flour_mill_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flour_mill
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize with SQL file if needed
    networks:
      - flour_mill_net

networks:
  flour_mill_net:
    driver: bridge

volumes:
  db_data:
