# Use Ubuntu as the base image
FROM ubuntu:22.04



# Enable Apache mods and set up permissions
RUN a2enmod php7.4 && a2enmod rewrite

# Set the working directory
WORKDIR /var/www/html

# Copy website files into the container
COPY ./www /var/www/html

# Set Apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

# Expose port 80
EXPOSE 80

# Start Apache
CMD ["apache2ctl", "-D", "FOREGROUND"]
