version: '3.3'

services:
  web:
    image: php:7.4-apache
    container_name: flour_mill_web
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=accounting
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword

  db:
    image: mysql:5.6
    container_name: flour_mill_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: accounting
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
